name: swimburger-blazor-wasm
static_sites:
- name: site
  github:
    repo: rheer/BlazorWasmDigitalOcean
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.build 
  output_dir: /output/wwwroot
  index_document: index.html
  catchall_document: index.html
